export const MIN_PLAYABLE_BALANCE = 1;
export const DEFAULT_STARTING_BALANCE = 100000;
export const MAX_PLAYER_TOTAL_BET = 100000;
export const MAX_TOTAL_PLAYERS = 8;
export const MAX_TOURNAMENT_PARTICIPANTS = 128;

export const SMALL_BLIND_AMOUNT = 2000;
export const BIG_BLIND_AMOUNT = 5000;
export const MAX_TOURNAMENT_BLIND_LEVEL = MAX_PLAYER_TOTAL_BET / BIG_BLIND_AMOUNT;

export const DEFAULT_COMPUTER_ACTION_DELAY_MS = 700;
export const DEFAULT_NEXT_HAND_DELAY_MS = 1800;
export const DEFAULT_HUMAN_ACTION_TIMEOUT_MS = 15000;

export const MIN_COMPUTER_ACTION_DELAY_MS = 100;
export const MAX_COMPUTER_ACTION_DELAY_MS = 3000;
export const MIN_NEXT_HAND_DELAY_MS = 500;
export const MAX_NEXT_HAND_DELAY_MS = 10000;
export const MIN_HUMAN_ACTION_TIMEOUT_MS = 3000;
export const MAX_HUMAN_ACTION_TIMEOUT_MS = 60000;

export const MIN_MULTIPLAYER_HUMAN_SLOTS = 1;
export const MAX_MULTIPLAYER_HUMAN_SLOTS = MAX_TOTAL_PLAYERS;
export const MULTIPLAYER_RECONNECT_DELAY_MS = 1500;
